In [97]:
import pandas as pd

# Series

In [98]:
import numpy as np
arr = np.arange(100,110)
print(arr)

[100 101 102 103 104 105 106 107 108 109]


In [99]:
s = pd.Series(arr) #클래스 인스턴스화
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int64


In [100]:
s = pd.Series(arr, dtype='int32')
print(s)

0    100
1    101
2    102
3    103
4    104
5    105
6    106
7    107
8    108
9    109
dtype: int32


In [101]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)
print(s)

0     kim
1     lee
2    park
3    hong
dtype: object


In [102]:
s = pd.Series([1, 2, 3, 4, 5, '99'])
print(s)

0     1
1     2
2     3
3     4
4     5
5    99
dtype: object


# indexing

In [103]:
person = ['kim', 'lee', 'park', 'hong']
s = pd.Series(person)

In [104]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [105]:
s[3]

'hong'

In [107]:
s = pd.Series(person, index=['a', 'b', 'c', 'd'])
#동일 기능 : s = pd.Series(person, index=list('abcd'))
print(s)

a     kim
b     lee
c    park
d    hong
dtype: object


In [18]:
s['a']

'kim'

In [20]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [21]:
s.values

array(['kim', 'lee', 'park', 'hong'], dtype=object)

In [22]:
s.ndim #차원표시

1

In [23]:
s.shape #열과행표시?

(4,)

# NaN(Not A Number:결측치)

In [25]:
s = pd.Series(person + [np.nan])
print(s)

0     kim
1     lee
2    park
3    hong
4     NaN
dtype: object


In [28]:
50.0
51.0
52.0
53.0
54.0

arr = np.arange(50,55)
s = pd.Series(arr, dtype='float32')

In [29]:
print(s)

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32


In [109]:
f = ['바나나', np.nan,'사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마')) #변수 선언과 값 지정을 잘 해주자!!!!!!!!!!!!!!!!!!
print(s)

가    바나나
나    NaN
다     사과
라     포도
마    복숭아
dtype: object


# fancy indexing

In [111]:
#동일 기능 : s.iloc[[2,3]] (원하는 행, 렬 추출하기)
s[['다', '라']]

다    사과
라    포도
dtype: object

# bool (p.149)
*어떻게 사용하는거지?*

In [113]:
s[[True, False, True, False, True]]

가    바나나
다     사과
마    복숭아
dtype: object

In [114]:
a = [True, False, False, True, True]
s[a]

가    바나나
라     포도
마    복숭아
dtype: object

In [115]:
arr = np.arange(5, 20)
s = pd.Series(arr)
print(s)

0      5
1      6
2      7
3      8
4      9
5     10
6     11
7     12
8     13
9     14
10    15
11    16
12    17
13    18
14    19
dtype: int64


In [116]:
s<10

0      True
1      True
2      True
3      True
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [40]:
s[s<10]

0    5
1    6
2    7
3    8
4    9
dtype: int64

In [42]:
s[s == 5]

0    5
dtype: int64

# 결측치(Nan)처리

In [117]:
s = pd.Series([2, 5, np.nan ,58, 1, np.nan, 2, 4, 9, 11, np.nan])
print(s)

0      2.0
1      5.0
2      NaN
3     58.0
4      1.0
5      NaN
6      2.0
7      4.0
8      9.0
9     11.0
10     NaN
dtype: float64


In [118]:
s.isnull() #s[s.isnull()] 차이가 뭐야?

0     False
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [49]:
s[s.isnull()]

2    NaN
5    NaN
10   NaN
dtype: float64

In [50]:
s.isna()

0     False
1     False
2      True
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [51]:
s[s.isna()]

2    NaN
5    NaN
10   NaN
dtype: float64

In [52]:
s[s.notnull()]

0     2.0
1     5.0
3    58.0
4     1.0
6     2.0
7     4.0
8     9.0
9    11.0
dtype: float64

In [53]:
s[1:3]

1    5.0
2    NaN
dtype: float64

In [54]:
f = ['바나나', np.nan, '사과', '포도', '복숭아']
s = pd.Series(f, index=list('가나다라마'))
print(s['가':'라'])

가    바나나
나    NaN
다     사과
라     포도
dtype: object


# DataFrame

In [59]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [60]:
df = pd.DataFrame(arr)
print(df)
df

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8


0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [62]:
df = pd.DataFrame(
    arr,
    columns = ['가','나','다'],
    index = ['a','b','c'] #숫자 인덱스로 접근하는게 용이하기 때문에 잘 안바꿈
)
df

가  나  다
a  0  1  2
b  3  4  5
c  6  7  8

In [65]:

data = {
    'name' : ['kim', 'lee', 'park'],
    'age' : [10, 15, 20],
    'location' : ['Seoul', 'Gyeonggi', 'Busan']
}


df = pd.DataFrame(data)
df

name  age  location
0   kim   10     Seoul
1   lee   15  Gyeonggi
2  park   20     Busan

In [69]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [68]:
df.columns

Index(['name', 'age', 'location'], dtype='object')

In [70]:
df.values

array([['kim', 10, 'Seoul'],
       ['lee', 15, 'Gyeonggi'],
       ['park', 20, 'Busan']], dtype=object)

In [71]:
df.dtypes

name        object
age          int64
location    object
dtype: object

In [119]:
df.T #전치행렬

a         b      c
name        kim       lee   park
age          10        15     20
hometown  Seoul  Gyeonggi  Busan

In [120]:
df

name  age  hometown
a   kim   10     Seoul
b   lee   15  Gyeonggi
c  park   20     Busan

In [74]:
df.index = list('abc')
df

name  age  location
a   kim   10     Seoul
b   lee   15  Gyeonggi
c  park   20     Busan

# column

In [76]:
df['name'] #name 시리즈 (열별로 보라?)

a     kim
b     lee
c    park
Name: name, dtype: object

In [77]:
type(df['name'])

pandas.core.series.Series

In [78]:
df[['name', 'location']]

name  location
a   kim     Seoul
b   lee  Gyeonggi
c  park     Busan

In [80]:
type(df[['name','location']])

pandas.core.frame.DataFrame

In [86]:
#df.rename(columns={'location':'hometown'}) #<-원본을 바꾸려면 변수화?해주라
df = df.rename(columns={'location':'hometown'})
df

name  age  hometown
a   kim   10     Seoul
b   lee   15  Gyeonggi
c  park   20     Busan

In [88]:
#바로 원본을 수정하는 또 다른 코드
df.rename(columns={'location':'hometown'}, inplace=True)
df

name  age  hometown
a   kim   10     Seoul
b   lee   15  Gyeonggi
c  park   20     Busan